# Generated by Django 5.2.12 on 2026-04-16 07:02

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description_1', models.TextField()),
                ('description_2', models.TextField(blank=True, null=True)),
                ('mission_title', models.CharField(max_length=100)),
                ('mission_desc', models.TextField()),
                ('vision_title', models.CharField(max_length=100)),
                ('vision_desc', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
