# Generated by Django 5.2.12 on 2026-04-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whychooseus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whychooseus',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
